### ISSUE TITLE
controlled vocabulary

### ISSUE THREAD

**Issue by delahousse** [europarl/open-data-beta-testing#13]
It could be useful to have a documentation page with the links to the controlled vocabularies used in the dataset, as they have to be downloaded to use the data.

**Comment by andrea-perego** [comment]
Thanks for the suggestion, @delahousse . We'll take care of that, and inform you when done.

**Comment by andrea-perego** [comment]
This is issue is being addressed via PR https://github.com/europarl/open-data-beta-testing/pull/17

@delahousse , could you please review it?
